package com.finsight.backend.controller;

import com.finsight.backend.dto.AnomalyInsightDto;
import com.finsight.backend.dto.CategoryInsightDto;
import com.finsight.backend.dto.VendorInsightDto;
import com.finsight.backend.entity.ForensicAnomaly;
import com.finsight.backend.repository.ForensicAnomalyRepository;
import com.finsight.backend.service.AnomalyDetectionService;
import com.finsight.backend.service.VendorService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@RequestMapping("/api/v1/insights")
@CrossOrigin(origins = "*")
@Tag(name = "Financial Insights", description = "Endpoints for forensic anomalies, vendor trends, and categorizations")
public class InsightsController {

    private final VendorService vendorService;
    private final AnomalyDetectionService anomalyDetectionService;
    private final ForensicAnomalyRepository forensicAnomalyRepository;

    public InsightsController(VendorService vendorService, 
                              AnomalyDetectionService anomalyDetectionService,
                              ForensicAnomalyRepository forensicAnomalyRepository) {
        this.vendorService = vendorService;
        this.anomalyDetectionService = anomalyDetectionService;
        this.forensicAnomalyRepository = forensicAnomalyRepository;
    }

    @GetMapping("/vendors/top")
    @Operation(summary = "Get Top Vendors", description = "Retrieves a list of vendors ranked by total transaction volume.")
    public ResponseEntity<List<VendorInsightDto>> getTopVendors(
            @Parameter(description = "Maximum number of vendors to return") @RequestParam(defaultValue = "10") int limit) {
        return ResponseEntity.ok(vendorService.getTopVendors(limit));
    }

    @GetMapping({"/category-spending", "/categories/spend"})
    @Operation(summary = "Get Spend by Category", description = "Aggregates total spending grouped by inferred financial category.")
    public ResponseEntity<List<CategoryInsightDto>> getCategorySpending() {
        return ResponseEntity.ok(vendorService.getSpendingByCategory("local_tenant"));
    }

    @GetMapping("/anomalies/detect")
    @Operation(summary = "Run Anomaly Detection", description = "On-demand scan to identify suspected duplicate or abnormal transactions.")
    public ResponseEntity<?> runAnomalyDetection() {
        try {
            List<AnomalyInsightDto> anomalies = anomalyDetectionService.detectAnomalies();
            Map<String, Object> response = new HashMap<>();
            response.put("anomalies", anomalies);
            response.put("count", anomalies.size());
            return ResponseEntity.ok(response);
        } catch (IllegalStateException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("error", "Failed to run anomaly detection."));
        }
    }

    @GetMapping("/anomalies/history")
    @Operation(summary = "Get Anomaly History", description = "Retrieves previously detected financial forensic anomalies ordered by date.")
    public ResponseEntity<List<ForensicAnomaly>> getAnomalyHistory() {
        return ResponseEntity.ok(forensicAnomalyRepository.findByTenantIdOrderByTxDateDesc("local_tenant"));
    }

    @GetMapping("/categories/{categoryName}/drilldown")
    @Operation(summary = "Get Category Drilldown", description = "Provides detailed spending within a category, including top vendors and recent transactions.")
    public ResponseEntity<Map<String, Object>> getCategoryDrilldown(
            @Parameter(description = "Name of the category to drill down into") @PathVariable String categoryName) {
        return ResponseEntity.ok(vendorService.getCategoryDrilldown(categoryName, "local_tenant"));
    }

    @GetMapping("/ocr-stats")
    @Operation(summary = "Get OCR Accuracy Stats", description = "Provides statistics comparing high confidence metrics generated by the TrOCR engine.")
    public ResponseEntity<Map<String, Long>> getOcrStats() {
        return ResponseEntity.ok(vendorService.getOcrModeStats());
    }
}
